import { Presentation, PresentationSchema, SLIDE_WIDTH, SLIDE_HEIGHT } from "./schema";

/**
 * One hardcoded example slide, used to prove the render pipeline end to end
 * before any AI, auth, or database work exists.
 */
const raw = {
  id: "example-presentation",
  title: "Causes of World War I",
  theme: "academic",
  slides: [
    {
      id: "slide-1",
      layout: "title-body",
      background: "#1C1712",
      elements: [
        {
          type: "text",
          id: "title",
          role: "title",
          content: "Causes of World War I",
          fontFamily: "display",
          fontSize: 56,
          fontWeight: 400,
          color: "#F2E9DA",
          align: "left",
          lineHeight: 1.1,
          x: 80,
          y: 90,
          width: SLIDE_WIDTH - 160,
          height: 110,
        },
        {
          type: "shape",
          id: "accent-rule",
          shape: "rectangle",
          fill: "#D97A52",
          radius: 2,
          x: 80,
          y: 210,
          width: 72,
          height: 6,
        },
        {
          type: "text",
          id: "body",
          role: "body",
          content:
            "Four long-building tensions pulled Europe toward war in 1914: tangled alliance systems that turned a regional dispute into a continental one, an arms race between the great powers, rising nationalism in the Balkans and beyond, and a scramble for colonial and economic advantage. The assassination of Archduke Franz Ferdinand was the spark, not the cause.",
          fontFamily: "body",
          fontSize: 22,
          fontWeight: 400,
          color: "#F2E9DA",
          align: "left",
          lineHeight: 1.5,
          x: 80,
          y: 260,
          width: SLIDE_WIDTH - 160 - 420,
          height: 360,
        },
        {
          type: "text",
          id: "caption",
          role: "caption",
          content: "Academic theme · Slide 1 of 1",
          fontFamily: "body",
          fontSize: 14,
          fontWeight: 500,
          color: "#8FA389",
          align: "left",
          lineHeight: 1.3,
          x: 80,
          y: 640,
          width: 400,
          height: 24,
        },
        {
          type: "shape",
          id: "sidebar-card",
          shape: "rectangle",
          fill: "#2A231B",
          radius: 16,
          x: SLIDE_WIDTH - 420,
          y: 260,
          width: 340,
          height: 360,
        },
        {
          type: "text",
          id: "sidebar-label",
          role: "label",
          content: "KEY FACTOR",
          fontFamily: "body",
          fontSize: 13,
          fontWeight: 600,
          color: "#8FA389",
          align: "left",
          lineHeight: 1.2,
          x: SLIDE_WIDTH - 388,
          y: 292,
          width: 276,
          height: 20,
        },
        {
          type: "text",
          id: "sidebar-body",
          role: "body",
          content: "Alliance systems meant no conflict could stay local — a dispute between two countries pulled in six more within a week.",
          fontFamily: "body",
          fontSize: 19,
          fontWeight: 400,
          color: "#F2E9DA",
          align: "left",
          lineHeight: 1.45,
          x: SLIDE_WIDTH - 388,
          y: 324,
          width: 276,
          height: 260,
        },
      ],
    },
  ],
};

export const examplePresentation: Presentation = PresentationSchema.parse(raw);
