import { Presentation, PresentationSchema, SLIDE_WIDTH } from "./schema";

/**
 * Three hand-authored slides, used to prove multi-slide navigation and
 * theme switching before any AI, auth, or database work exists. Every
 * color is a role (see ColorRoleSchema), not a literal hex — that's what
 * lets the theme switcher actually restyle these.
 */
const raw = {
  id: "example-presentation",
  title: "Causes of World War I",
  theme: "academic",
  slides: [
    {
      id: "slide-1",
      layout: "title-body",
      background: "background",
      elements: [
        {
          type: "text",
          id: "s1-title",
          role: "title",
          content: "Causes of World War I",
          fontFamily: "display",
          fontSize: 56,
          fontWeight: 400,
          color: "text",
          align: "left",
          lineHeight: 1.1,
          x: 80,
          y: 90,
          width: SLIDE_WIDTH - 160,
          height: 110,
        },
        {
          type: "shape",
          id: "s1-accent-rule",
          shape: "rectangle",
          fill: "accent",
          radius: 2,
          x: 80,
          y: 210,
          width: 72,
          height: 6,
        },
        {
          type: "text",
          id: "s1-body",
          role: "body",
          content:
            "Four long-building tensions pulled Europe toward war in 1914: tangled alliance systems that turned a regional dispute into a continental one, an arms race between the great powers, rising nationalism in the Balkans and beyond, and a scramble for colonial and economic advantage. The assassination of Archduke Franz Ferdinand was the spark, not the cause.",
          fontFamily: "body",
          fontSize: 22,
          fontWeight: 400,
          color: "text",
          align: "left",
          lineHeight: 1.5,
          x: 80,
          y: 260,
          width: SLIDE_WIDTH - 160 - 420,
          height: 360,
        },
        {
          type: "text",
          id: "s1-caption",
          role: "caption",
          content: "Academic theme · Slide 1 of 5",
          fontFamily: "body",
          fontSize: 14,
          fontWeight: 500,
          color: "muted",
          align: "left",
          lineHeight: 1.3,
          x: 80,
          y: 640,
          width: 400,
          height: 24,
        },
        {
          type: "shape",
          id: "s1-sidebar-card",
          shape: "rectangle",
          fill: "surface",
          radius: 16,
          x: SLIDE_WIDTH - 420,
          y: 260,
          width: 340,
          height: 360,
        },
        {
          type: "text",
          id: "s1-sidebar-label",
          role: "label",
          content: "KEY FACTOR",
          fontFamily: "body",
          fontSize: 13,
          fontWeight: 600,
          color: "muted",
          align: "left",
          lineHeight: 1.2,
          x: SLIDE_WIDTH - 388,
          y: 292,
          width: 276,
          height: 20,
        },
        {
          type: "text",
          id: "s1-sidebar-body",
          role: "body",
          content:
            "Alliance systems meant no conflict could stay local — a dispute between two countries pulled in six more within a week.",
          fontFamily: "body",
          fontSize: 19,
          fontWeight: 400,
          color: "text",
          align: "left",
          lineHeight: 1.45,
          x: SLIDE_WIDTH - 388,
          y: 324,
          width: 276,
          height: 260,
        },
      ],
    },
    {
      id: "slide-2",
      layout: "big-statistic",
      background: "background",
      elements: [
        {
          type: "text",
          id: "s2-label",
          role: "label",
          content: "BY THE NUMBERS",
          fontFamily: "body",
          fontSize: 16,
          fontWeight: 600,
          color: "muted",
          align: "center",
          lineHeight: 1.2,
          x: 140,
          y: 150,
          width: SLIDE_WIDTH - 280,
          height: 28,
        },
        {
          type: "text",
          id: "s2-stat",
          role: "title",
          content: "65 million+",
          fontFamily: "display",
          fontSize: 110,
          fontWeight: 400,
          color: "accent",
          align: "center",
          lineHeight: 1,
          x: 100,
          y: 240,
          width: SLIDE_WIDTH - 200,
          height: 150,
        },
        {
          type: "shape",
          id: "s2-rule",
          shape: "rectangle",
          fill: "muted",
          radius: 2,
          x: SLIDE_WIDTH / 2 - 40,
          y: 410,
          width: 80,
          height: 4,
        },
        {
          type: "text",
          id: "s2-body",
          role: "body",
          content: "soldiers were mobilized across Europe by 1918 — more than any conflict before it.",
          fontFamily: "body",
          fontSize: 24,
          fontWeight: 400,
          color: "text",
          align: "center",
          lineHeight: 1.5,
          x: 240,
          y: 450,
          width: SLIDE_WIDTH - 480,
          height: 120,
        },
        {
          type: "text",
          id: "s2-caption",
          role: "caption",
          content: "Academic theme · Slide 2 of 5",
          fontFamily: "body",
          fontSize: 14,
          fontWeight: 500,
          color: "muted",
          align: "left",
          lineHeight: 1.3,
          x: 80,
          y: 640,
          width: 400,
          height: 24,
        },
      ],
    },
    {
      id: "slide-3",
      layout: "quote",
      background: "surface",
      elements: [
        {
          type: "text",
          id: "s3-quote",
          role: "title",
          content: "“The war to end all wars.”",
          fontFamily: "display",
          fontSize: 48,
          fontWeight: 400,
          color: "text",
          align: "center",
          lineHeight: 1.3,
          x: 160,
          y: 260,
          width: SLIDE_WIDTH - 320,
          height: 180,
        },
        {
          type: "shape",
          id: "s3-rule",
          shape: "rectangle",
          fill: "accent",
          radius: 2,
          x: SLIDE_WIDTH / 2 - 36,
          y: 450,
          width: 72,
          height: 4,
        },
        {
          type: "text",
          id: "s3-attribution",
          role: "caption",
          content: "— H. G. Wells, 1914",
          fontFamily: "body",
          fontSize: 18,
          fontWeight: 500,
          color: "muted",
          align: "center",
          lineHeight: 1.4,
          x: 160,
          y: 480,
          width: SLIDE_WIDTH - 320,
          height: 32,
        },
        {
          type: "text",
          id: "s3-caption",
          role: "caption",
          content: "Academic theme · Slide 3 of 5",
          fontFamily: "body",
          fontSize: 14,
          fontWeight: 500,
          color: "muted",
          align: "left",
          lineHeight: 1.3,
          x: 80,
          y: 640,
          width: 400,
          height: 24,
        },
      ],
    },
    {
      id: "slide-4",
      layout: "chart",
      background: "background",
      elements: [
        {
          type: "text",
          id: "s4-title",
          role: "title",
          content: "Soldiers Mobilized by 1914",
          fontFamily: "display",
          fontSize: 40,
          fontWeight: 400,
          color: "text",
          align: "left",
          lineHeight: 1.15,
          x: 80,
          y: 80,
          width: SLIDE_WIDTH - 160,
          height: 60,
        },
        {
          type: "line",
          id: "s4-rule",
          color: "accent",
          thickness: 4,
          x: 80,
          y: 148,
          width: 72,
          height: 4,
        },
        {
          type: "chart",
          id: "s4-chart",
          chartType: "bar",
          data: [
            { label: "Russia", value: 5300000 },
            { label: "Germany", value: 4500000 },
            { label: "France", value: 3800000 },
            { label: "Britain", value: 1000000 },
            { label: "Austria-Hungary", value: 3000000 },
          ],
          x: 80,
          y: 190,
          width: 740,
          height: 380,
        },
        {
          type: "shape",
          id: "s4-sidebar-card",
          shape: "rectangle",
          fill: "surface",
          radius: 16,
          x: SLIDE_WIDTH - 420,
          y: 190,
          width: 340,
          height: 380,
        },
        {
          type: "text",
          id: "s4-sidebar-label",
          role: "label",
          content: "TAKEAWAY",
          fontFamily: "body",
          fontSize: 13,
          fontWeight: 600,
          color: "muted",
          align: "left",
          lineHeight: 1.2,
          x: SLIDE_WIDTH - 388,
          y: 222,
          width: 276,
          height: 20,
        },
        {
          type: "text",
          id: "s4-sidebar-body",
          role: "body",
          content:
            "Russia fielded the largest army, but Germany's was the most rapidly mobilized — a key reason its war plan depended on speed.",
          fontFamily: "body",
          fontSize: 19,
          fontWeight: 400,
          color: "text",
          align: "left",
          lineHeight: 1.45,
          x: SLIDE_WIDTH - 388,
          y: 254,
          width: 276,
          height: 300,
        },
        {
          type: "text",
          id: "s4-caption",
          role: "caption",
          content: "Academic theme · Slide 4 of 5",
          fontFamily: "body",
          fontSize: 14,
          fontWeight: 500,
          color: "muted",
          align: "left",
          lineHeight: 1.3,
          x: 80,
          y: 640,
          width: 400,
          height: 24,
        },
      ],
    },
    {
      id: "slide-5",
      layout: "table",
      background: "surface",
      elements: [
        {
          type: "text",
          id: "s5-title",
          role: "title",
          content: "The Two Alliance Blocs",
          fontFamily: "display",
          fontSize: 40,
          fontWeight: 400,
          color: "text",
          align: "left",
          lineHeight: 1.15,
          x: 80,
          y: 80,
          width: SLIDE_WIDTH - 160,
          height: 60,
        },
        {
          type: "line",
          id: "s5-rule",
          color: "accent",
          thickness: 4,
          x: 80,
          y: 148,
          width: 72,
          height: 4,
        },
        {
          type: "table",
          id: "s5-table",
          rows: [
            ["", "Triple Entente", "Triple Alliance"],
            ["Core members", "Russia, France, Britain", "Germany, Austria-Hungary, Italy"],
            ["Formed", "1907", "1882"],
            ["Entered the war as", "Allied Powers", "Central Powers"],
          ],
          x: 80,
          y: 190,
          width: SLIDE_WIDTH - 160,
          height: 300,
        },
        {
          type: "text",
          id: "s5-caption",
          role: "caption",
          content: "Academic theme · Slide 5 of 5",
          fontFamily: "body",
          fontSize: 14,
          fontWeight: 500,
          color: "muted",
          align: "left",
          lineHeight: 1.3,
          x: 80,
          y: 640,
          width: 400,
          height: 24,
        },
      ],
    },
  ],
};

export const examplePresentation: Presentation = PresentationSchema.parse(raw);
